### PR TITLE
Simplified Chinese Localization

### PR DESCRIPTION
**Pull request by suliveevil**
Simplified Chinese Localization

### CODE REVIEW

**Comment by suliveevil** [comment]
I'm not a iOS/iPadOS/macOS developer.
If there are mistakes, correct me, thanks!

**Comment by ObuchiYuki** [comment]
@suliveevil Thank you for your work! 
There seem to be several problems with this PR

1. The Git Conflict does not seem to have been resolved.
2. The content may be identical to this PR. https://github.com/ObuchiYuki/DevToysMac/pull/33
It looks like the PR is not in Traditional Chinese.

**Comment by wibus-wee** [comment]
There seems to be some incorrect code?

**Comment by suliveevil** [comment]
Sorry for not seeing it before, I will close this PR.

**Comment by suliveevil** [comment]
> 1. The Git Conflict does not seem to have been resolved.
I use the app Stringz to edit, when I first PR it has no conflicts, next time I will focus on `zh-Hans.lproj` instead of Stringz's setting.
> 2. The content may be identical to this PR. [Chinese localization support #33](https://github.com/ObuchiYuki/DevToysMac/pull/33)
Sorry for didn't notice that before.

**Pull request closed without merging**
