### PR TITLE
feat(translations): Add pt-BR localization strings

### PR DESCRIPTION
**Pull request by DanielSouzaBertoldi**
This PR translates both `Localizable.strings` and `Main.strings` to Brazilian Portuguese.

Evidences:

image

**Note:** Unfortunately the description for both URL and HTML decoder/encoder ended up a little bigger than the card. Is there something I can do about it?

Kapture 2022-02-14 at 07 31 52

This is my first time ever contributing to a project written in Swift, so if anything's wrong please tell me :)

### CODE REVIEW

**Review by mattvasc — APPROVED** [review]
I'm a Brazilian dude, and I did liked the translations.

**Comment by JhonataCampos** [comment]
Pretty solid translations. Keep up the good work!! Recommended.

**Comment by tlacerdat** [comment]
Nice job, as a **Brazilian**, I can say that the translation was incredible.

**Comment by carlagaama** [comment]
Great job on this translation! So detailed that people won't have to use Google translate anymore.

**Review by lubuzzo — APPROVED** [review]

**Comment by lubuzzo** [comment]
**LGTM**.

I recently started using DevToysMac instead of a couple of different websites, specific for each task - this translation can help even more my life, and other portuguese programmers.

**Comment by ObuchiYuki** [comment]
@DanielSouzaBertoldi @mattvasc @JhonataCampos @carlagaama @lubuzzo 
Thank you for your PR and translation checks! The translation work is very helpful, and I'm glad DevToys for Mac is helping you!

**Pull request merged**
